#!/usr/bin/env bash
# ==============================================================================
# Shared Helper: Resolve MS Teams Target Webhooks by Deployment Environment
# Populates the TARGET_WEBHOOKS array based on $DEPLOY_NAME or $1.
# ==============================================================================

TARGET_ENV="${1:-$DEPLOY_NAME}"
NORM_ENV=$(echo "$TARGET_ENV" | tr '[:upper:]' '[:lower:]' | sed -e 's/[^a-z0-9]//g')
TARGET_WEBHOOKS=()

case "$NORM_ENV" in
  # ── Core Environments ──────────────────────────────────────────
  "ais02"|"asintais02")
    [ -n "$TEAMS_WEBHOOK_AIS02_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_AIS02_1")
    [ -n "$TEAMS_WEBHOOK_AIS02_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_AIS02_2")
    [ -n "$TEAMS_WEBHOOK_AIS02_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_AIS02_3")
    ;;
  "apm01"|"asintapm01")
    [ -n "$TEAMS_WEBHOOK_APM01_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APM01_1")
    [ -n "$TEAMS_WEBHOOK_APM01_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APM01_2")
    [ -n "$TEAMS_WEBHOOK_APM01_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APM01_3")
    ;;
  "apm02"|"asintapm02")
    [ -n "$TEAMS_WEBHOOK_APM02_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APM02_1")
    [ -n "$TEAMS_WEBHOOK_APM02_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APM02_2")
    [ -n "$TEAMS_WEBHOOK_APM02_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APM02_3")
    ;;
  "apmeiot"|"asintapmeiot")
    [ -n "$TEAMS_WEBHOOK_APMEIOT_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APMEIOT_1")
    [ -n "$TEAMS_WEBHOOK_APMEIOT_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APMEIOT_2")
    [ -n "$TEAMS_WEBHOOK_APMEIOT_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APMEIOT_3")
    ;;
  "demo"|"asintdemo")
    [ -n "$TEAMS_WEBHOOK_DEMO_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_DEMO_1")
    [ -n "$TEAMS_WEBHOOK_DEMO_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_DEMO_2")
    [ -n "$TEAMS_WEBHOOK_DEMO_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_DEMO_3")
    ;;
  "baystar"|"asintbaystar")
    [ -n "$TEAMS_WEBHOOK_BAYSTAR_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_BAYSTAR_1")
    [ -n "$TEAMS_WEBHOOK_BAYSTAR_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_BAYSTAR_2")
    [ -n "$TEAMS_WEBHOOK_BAYSTAR_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_BAYSTAR_3")
    ;;
  "hscnonprod"|"hemlocknonprod")
    [ -n "$TEAMS_WEBHOOK_HSC_NON_PROD_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_HSC_NON_PROD_1")
    [ -n "$TEAMS_WEBHOOK_HSC_NON_PROD_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_HSC_NON_PROD_2")
    [ -n "$TEAMS_WEBHOOK_HSC_NON_PROD_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_HSC_NON_PROD_3")
    ;;
  "hscprod"|"hemlockprod")
    [ -n "$TEAMS_WEBHOOK_HSC_PROD_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_HSC_PROD_1")
    [ -n "$TEAMS_WEBHOOK_HSC_PROD_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_HSC_PROD_2")
    [ -n "$TEAMS_WEBHOOK_HSC_PROD_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_HSC_PROD_3")
    ;;
  "indoramaprod900"|"asintindoramaprod900")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_PROD_900_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_PROD_900_1")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_PROD_900_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_PROD_900_2")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_PROD_900_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_PROD_900_3")
    ;;
  "indoramaprod933"|"asintindoramaprod933")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_PROD_933_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_PROD_933_1")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_PROD_933_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_PROD_933_2")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_PROD_933_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_PROD_933_3")
    ;;
  "indoramaqa233"|"asintindoramaqa233")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_QA_233_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_QA_233_1")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_QA_233_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_QA_233_2")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_QA_233_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_QA_233_3")
    ;;
  "indoramaqa234"|"asintindoramaqa234")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_QA_234_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_QA_234_1")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_QA_234_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_QA_234_2")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_QA_234_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_QA_234_3")
    ;;
  "irc"|"asintirc")
    [ -n "$TEAMS_WEBHOOK_IRC_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_IRC_1")
    [ -n "$TEAMS_WEBHOOK_IRC_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_IRC_2")
    [ -n "$TEAMS_WEBHOOK_IRC_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_IRC_3")
    ;;
  "stenv"|"asintst")
    [ -n "$TEAMS_WEBHOOK_ST_ENV_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_ST_ENV_1")
    [ -n "$TEAMS_WEBHOOK_ST_ENV_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_ST_ENV_2")
    [ -n "$TEAMS_WEBHOOK_ST_ENV_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_ST_ENV_3")
    ;;
  "vmos"|"asintvmos")
    [ -n "$TEAMS_WEBHOOK_VMOS_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_VMOS_1")
    [ -n "$TEAMS_WEBHOOK_VMOS_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_VMOS_2")
    [ -n "$TEAMS_WEBHOOK_VMOS_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_VMOS_3")
    ;;

  # ── DC Environments ────────────────────────────────────────────
  "ais02dc"|"asintais02dc")
    [ -n "$TEAMS_WEBHOOK_AIS02_DC_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_AIS02_DC_1")
    [ -n "$TEAMS_WEBHOOK_AIS02_DC_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_AIS02_DC_2")
    [ -n "$TEAMS_WEBHOOK_AIS02_DC_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_AIS02_DC_3")
    ;;
  "apm01dc"|"asintapm01dc")
    [ -n "$TEAMS_WEBHOOK_APM01_DC_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APM01_DC_1")
    [ -n "$TEAMS_WEBHOOK_APM01_DC_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APM01_DC_2")
    [ -n "$TEAMS_WEBHOOK_APM01_DC_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APM01_DC_3")
    ;;
  "apm02dc"|"asintapm02dc")
    [ -n "$TEAMS_WEBHOOK_APM02_DC_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APM02_DC_1")
    [ -n "$TEAMS_WEBHOOK_APM02_DC_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APM02_DC_2")
    [ -n "$TEAMS_WEBHOOK_APM02_DC_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APM02_DC_3")
    ;;
  "apmeiotdc"|"asintapmeiotdc")
    [ -n "$TEAMS_WEBHOOK_APMEIOT_DC_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APMEIOT_DC_1")
    [ -n "$TEAMS_WEBHOOK_APMEIOT_DC_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APMEIOT_DC_2")
    [ -n "$TEAMS_WEBHOOK_APMEIOT_DC_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APMEIOT_DC_3")
    ;;
  "demodc"|"asintdemodc")
    [ -n "$TEAMS_WEBHOOK_DEMO_DC_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_DEMO_DC_1")
    [ -n "$TEAMS_WEBHOOK_DEMO_DC_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_DEMO_DC_2")
    [ -n "$TEAMS_WEBHOOK_DEMO_DC_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_DEMO_DC_3")
    ;;
  "baystardc"|"asintbaystardc")
    [ -n "$TEAMS_WEBHOOK_BAYSTAR_DC_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_BAYSTAR_DC_1")
    [ -n "$TEAMS_WEBHOOK_BAYSTAR_DC_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_BAYSTAR_DC_2")
    [ -n "$TEAMS_WEBHOOK_BAYSTAR_DC_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_BAYSTAR_DC_3")
    ;;
  "hscnonproddc"|"hemlocknonproddc")
    [ -n "$TEAMS_WEBHOOK_HSC_NON_PROD_DC_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_HSC_NON_PROD_DC_1")
    [ -n "$TEAMS_WEBHOOK_HSC_NON_PROD_DC_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_HSC_NON_PROD_DC_2")
    [ -n "$TEAMS_WEBHOOK_HSC_NON_PROD_DC_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_HSC_NON_PROD_DC_3")
    ;;
  "hscproddc"|"hemlockproddc")
    [ -n "$TEAMS_WEBHOOK_HSC_PROD_DC_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_HSC_PROD_DC_1")
    [ -n "$TEAMS_WEBHOOK_HSC_PROD_DC_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_HSC_PROD_DC_2")
    [ -n "$TEAMS_WEBHOOK_HSC_PROD_DC_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_HSC_PROD_DC_3")
    ;;
  "indoramaprod900dc"|"asintindoramaprod900dc")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_PROD_900_DC_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_PROD_900_DC_1")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_PROD_900_DC_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_PROD_900_DC_2")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_PROD_900_DC_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_PROD_900_DC_3")
    ;;
  "indoramaprod933dc"|"asintindoramaprod933dc")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_PROD_933_DC_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_PROD_933_DC_1")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_PROD_933_DC_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_PROD_933_DC_2")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_PROD_933_DC_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_PROD_933_DC_3")
    ;;
  "indoramaqa233dc"|"asintindoramaqa233dc")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_QA_233_DC_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_QA_233_DC_1")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_QA_233_DC_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_QA_233_DC_2")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_QA_233_DC_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_QA_233_DC_3")
    ;;
  "indoramaqa234dc"|"asintindoramaqa234dc")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_QA_234_DC_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_QA_234_DC_1")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_QA_234_DC_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_QA_234_DC_2")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_QA_234_DC_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_QA_234_DC_3")
    ;;
  "ircdc"|"asintircdc")
    [ -n "$TEAMS_WEBHOOK_IRC_DC_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_IRC_DC_1")
    [ -n "$TEAMS_WEBHOOK_IRC_DC_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_IRC_DC_2")
    [ -n "$TEAMS_WEBHOOK_IRC_DC_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_IRC_DC_3")
    ;;
  "stenvdc"|"asintstdc")
    [ -n "$TEAMS_WEBHOOK_ST_ENV_DC_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_ST_ENV_DC_1")
    [ -n "$TEAMS_WEBHOOK_ST_ENV_DC_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_ST_ENV_DC_2")
    [ -n "$TEAMS_WEBHOOK_ST_ENV_DC_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_ST_ENV_DC_3")
    ;;
  "vmosdc"|"asintvmosdc")
    [ -n "$TEAMS_WEBHOOK_VMOS_DC_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_VMOS_DC_1")
    [ -n "$TEAMS_WEBHOOK_VMOS_DC_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_VMOS_DC_2")
    [ -n "$TEAMS_WEBHOOK_VMOS_DC_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_VMOS_DC_3")
    ;;

  # ── DC AddIn Environments ──────────────────────────────────────
  "ais02dcaddin"|"asintais02dcaddin")
    [ -n "$TEAMS_WEBHOOK_AIS02_DC_ADDIN_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_AIS02_DC_ADDIN_1")
    [ -n "$TEAMS_WEBHOOK_AIS02_DC_ADDIN_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_AIS02_DC_ADDIN_2")
    [ -n "$TEAMS_WEBHOOK_AIS02_DC_ADDIN_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_AIS02_DC_ADDIN_3")
    ;;
  "apm01dcaddin"|"asintapm01dcaddin")
    [ -n "$TEAMS_WEBHOOK_APM01_DC_ADDIN_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APM01_DC_ADDIN_1")
    [ -n "$TEAMS_WEBHOOK_APM01_DC_ADDIN_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APM01_DC_ADDIN_2")
    [ -n "$TEAMS_WEBHOOK_APM01_DC_ADDIN_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APM01_DC_ADDIN_3")
    ;;
  "apm02dcaddin"|"asintapm02dcaddin")
    [ -n "$TEAMS_WEBHOOK_APM02_DC_ADDIN_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APM02_DC_ADDIN_1")
    [ -n "$TEAMS_WEBHOOK_APM02_DC_ADDIN_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APM02_DC_ADDIN_2")
    [ -n "$TEAMS_WEBHOOK_APM02_DC_ADDIN_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APM02_DC_ADDIN_3")
    ;;
  "apmeiotdcaddin"|"asintapmeiotdcaddin")
    [ -n "$TEAMS_WEBHOOK_APMEIOT_DC_ADDIN_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APMEIOT_DC_ADDIN_1")
    [ -n "$TEAMS_WEBHOOK_APMEIOT_DC_ADDIN_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APMEIOT_DC_ADDIN_2")
    [ -n "$TEAMS_WEBHOOK_APMEIOT_DC_ADDIN_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_APMEIOT_DC_ADDIN_3")
    ;;
  "demodcaddin"|"asintdemodcaddin")
    [ -n "$TEAMS_WEBHOOK_DEMO_DC_ADDIN_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_DEMO_DC_ADDIN_1")
    [ -n "$TEAMS_WEBHOOK_DEMO_DC_ADDIN_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_DEMO_DC_ADDIN_2")
    [ -n "$TEAMS_WEBHOOK_DEMO_DC_ADDIN_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_DEMO_DC_ADDIN_3")
    ;;
  "baystardcaddin"|"asintbaystardcaddin")
    [ -n "$TEAMS_WEBHOOK_BAYSTAR_DC_ADDIN_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_BAYSTAR_DC_ADDIN_1")
    [ -n "$TEAMS_WEBHOOK_BAYSTAR_DC_ADDIN_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_BAYSTAR_DC_ADDIN_2")
    [ -n "$TEAMS_WEBHOOK_BAYSTAR_DC_ADDIN_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_BAYSTAR_DC_ADDIN_3")
    ;;
  "hscnonproddcaddin"|"hemlocknonproddcaddin")
    [ -n "$TEAMS_WEBHOOK_HSC_NON_PROD_DC_ADDIN_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_HSC_NON_PROD_DC_ADDIN_1")
    [ -n "$TEAMS_WEBHOOK_HSC_NON_PROD_DC_ADDIN_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_HSC_NON_PROD_DC_ADDIN_2")
    [ -n "$TEAMS_WEBHOOK_HSC_NON_PROD_DC_ADDIN_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_HSC_NON_PROD_DC_ADDIN_3")
    ;;
  "hscproddcaddin"|"hemlockproddcaddin")
    [ -n "$TEAMS_WEBHOOK_HSC_PROD_DC_ADDIN_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_HSC_PROD_DC_ADDIN_1")
    [ -n "$TEAMS_WEBHOOK_HSC_PROD_DC_ADDIN_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_HSC_PROD_DC_ADDIN_2")
    [ -n "$TEAMS_WEBHOOK_HSC_PROD_DC_ADDIN_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_HSC_PROD_DC_ADDIN_3")
    ;;
  "indoramaprod900dcaddin"|"asintindoramaprod900dcaddin")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_PROD_900_DC_ADDIN_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_PROD_900_DC_ADDIN_1")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_PROD_900_DC_ADDIN_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_PROD_900_DC_ADDIN_2")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_PROD_900_DC_ADDIN_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_PROD_900_DC_ADDIN_3")
    ;;
  "indoramaprod933dcaddin"|"asintindoramaprod933dcaddin")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_PROD_933_DC_ADDIN_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_PROD_933_DC_ADDIN_1")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_PROD_933_DC_ADDIN_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_PROD_933_DC_ADDIN_2")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_PROD_933_DC_ADDIN_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_PROD_933_DC_ADDIN_3")
    ;;
  "indoramaqa233dcaddin"|"asintindoramaqa233dcaddin")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_QA_233_DC_ADDIN_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_QA_233_DC_ADDIN_1")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_QA_233_DC_ADDIN_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_QA_233_DC_ADDIN_2")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_QA_233_DC_ADDIN_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_QA_233_DC_ADDIN_3")
    ;;
  "indoramaqa234dcaddin"|"asintindoramaqa234dcaddin")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_QA_234_DC_ADDIN_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_QA_234_DC_ADDIN_1")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_QA_234_DC_ADDIN_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_QA_234_DC_ADDIN_2")
    [ -n "$TEAMS_WEBHOOK_INDORAMA_QA_234_DC_ADDIN_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_INDORAMA_QA_234_DC_ADDIN_3")
    ;;
  "ircdcaddin"|"asintircdcaddin")
    [ -n "$TEAMS_WEBHOOK_IRC_DC_ADDIN_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_IRC_DC_ADDIN_1")
    [ -n "$TEAMS_WEBHOOK_IRC_DC_ADDIN_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_IRC_DC_ADDIN_2")
    [ -n "$TEAMS_WEBHOOK_IRC_DC_ADDIN_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_IRC_DC_ADDIN_3")
    ;;
  "stenvdcaddin"|"asintstdcaddin")
    [ -n "$TEAMS_WEBHOOK_ST_ENV_DC_ADDIN_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_ST_ENV_DC_ADDIN_1")
    [ -n "$TEAMS_WEBHOOK_ST_ENV_DC_ADDIN_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_ST_ENV_DC_ADDIN_2")
    [ -n "$TEAMS_WEBHOOK_ST_ENV_DC_ADDIN_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_ST_ENV_DC_ADDIN_3")
    ;;
  "vmosdcaddin"|"asintvmosdcaddin")
    [ -n "$TEAMS_WEBHOOK_VMOS_DC_ADDIN_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_VMOS_DC_ADDIN_1")
    [ -n "$TEAMS_WEBHOOK_VMOS_DC_ADDIN_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_VMOS_DC_ADDIN_2")
    [ -n "$TEAMS_WEBHOOK_VMOS_DC_ADDIN_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_VMOS_DC_ADDIN_3")
    ;;
esac

# Always include Global Webhook URLs for universal notification broadcast
[ -n "$TEAMS_WEBHOOK_GLOBAL_1" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_GLOBAL_1")
[ -n "$TEAMS_WEBHOOK_GLOBAL_2" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_GLOBAL_2")
[ -n "$TEAMS_WEBHOOK_GLOBAL_3" ] && TARGET_WEBHOOKS+=("$TEAMS_WEBHOOK_GLOBAL_3")
