name: "Deploy: AsInt Demo"

on:
  repository_dispatch:
    types: [trigger_asint_demo_deployment]
  workflow_dispatch:

jobs:
  merging-process:
    uses: ./.github/workflows/_auto_merge.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      base: "tenant/asint-demo"
      compare: "main"
      deployment_name: "AsInt Demo"
      dashboard_url: "https://asint-payg-development.cicd.cfapps.eu10.hana.ondemand.com/ui/index.html#"
    secrets: inherit
