name: "Deploy: Indorama Prod 900"

on:
  repository_dispatch:
    types: [trigger_indorama_prod_900_deployment]
  workflow_dispatch:

jobs:
  merging-process:
    uses: ./.github/workflows/_auto_merge.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      base: "tenant/indorama-prod-900"
      compare: "tenant/indorama-qa-233"
      deployment_name: "Indorama Prod 900"
      dashboard_url: "https://asint-payg-development.cicd.cfapps.eu10.hana.ondemand.com/ui/index.html#"
    secrets: inherit
