name: "Deploy: APM-01"

on:
  repository_dispatch:
    types: [trigger_apm01_deployment]
  workflow_dispatch:

jobs:
  pre-stop-crawler:
    uses: ./.github/workflows/_cf_app_control.yml
    with:
      api_endpoint: "https://api.cf.eu10-004.hana.ondemand.com"
      org: "asint-apm-01"
      space: "demo"
      app_name: "crawler-layer-backend"
      action: "stop"
    secrets: inherit

  merging-process:
    needs: pre-stop-crawler
    uses: ./.github/workflows/_auto_merge.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      base: "tenant/asint-apm-01-new"
      compare: "main"
      deployment_name: "APM-01"
      dashboard_url: "https://asint-payg-development.cicd.cfapps.eu10.hana.ondemand.com/ui/index.html#"
    secrets: inherit
