name: "Deploy: VMOS DC AddIn"

on:
  repository_dispatch:
    types: [trigger_vmos_dc_addin_deployment]

jobs:
  merging-process:
    uses: ./.github/workflows/_auto_merge.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      base: "tenant/vmos-dc-addin"
      compare: "main-dc-addin"
      deployment_name: "VMOS DC AddIn"
      dashboard_url: "https://asint-payg-development.cicd.cfapps.eu10.hana.ondemand.com/ui/index.html#"
    secrets: inherit
