name: "Deploy: VMOS"

on:
  repository_dispatch:
    types: [trigger_vmos_deployment]

jobs:
  merging-process:
    uses: ./.github/workflows/_auto_merge.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      base: "tenant/vmos-dev"
      compare: "main"
      deployment_name: "VMOS"
      dashboard_url: "https://asint-payg-development.cicd.cfapps.eu10.hana.ondemand.com/ui/index.html#"
    secrets: inherit
