name: "Deploy: APM-EIOT"

on:
  repository_dispatch:
    types: [trigger_apm_eiot_deployment]
  workflow_dispatch:

jobs:
  merging-process:
    uses: ./.github/workflows/_auto_merge.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      base: "apm-eiot-temp-copy"
      compare: "main"
      deployment_name: "APM-EIOT"
      dashboard_url: "https://asint-payg-development.cicd.cfapps.eu10.hana.ondemand.com/ui/index.html#"
    secrets: inherit
