name: "Deploy: BAYSTAR DC"

on:
  repository_dispatch:
    types: [trigger_baystar_dc_deployment]

jobs:
  merging-process:
    uses: ./.github/workflows/_auto_merge.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      base: "tenant/baystar-dc"
      compare: "main-dc"
      deployment_name: "BAYSTAR DC"
      dashboard_url: "https://asint-payg-development.cicd.cfapps.eu10.hana.ondemand.com/ui/index.html#"
    secrets: inherit
