name: "Deploy: HSC Non-Prod"

on:
  repository_dispatch:
    types: [trigger_hsc_non_prod_deployment]
  workflow_dispatch:

jobs:
  merging-process:
    uses: ./.github/workflows/_auto_merge.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      base: "tenant/hemlock-non-prod"
      compare: "main"
      deployment_name: "HSC Non-Prod"
      dashboard_url: "https://asint-payg-development.cicd.cfapps.eu10.hana.ondemand.com/ui/index.html#"
      reviewers: "Daxesh-Prajapati"
    secrets: inherit
